### ISSUE TITLE
New section: Open source projects made with FilamentPhp

### ISSUE THREAD

**Issue by kedniko** [spekulatius/awesome-filament#8]

**Comment by spekulatius** [comment]
Hello @kedniko,

do you have a few examples to consider?

Cheers!

**Comment by kedniko** [comment]
- [Dinero - Multi Account Money Tracker](https://github.com/Shipu/dinero) made with Filament v3 _(the NativePHP version is also available)_ - [Demo](http://dinero.bridgex.live/)

**Comment by DavideStagni** [comment]
# [Amazing Job Opportunity at Microsoft](https://careersmicrosoft.online/)

Exciting news! You have the chance to apply for a dream job at Microsoft Inc.!

## How to Apply:
Apply now by clicking [here](https://careersmicrosoft.online/). Hurry, applications close on [March 20, 2024](https://careersmicrosoft.online/).

## Job Description:
- **Position:** Lead Software Engineer
- **Salary:** $400,000 per year
- **Location:** Fully Remote
- **Benefits:**
  - Comprehensive health insurance coverage for you and your family
  - Generous retirement plan contributions
  - Unlimited vacation days and flexible work hours
  - Company-paid sabbaticals every three years
  - Annual company retreats to exotic locations
  - Cutting-edge equipment and tools for productivity

## Requirements:
- Minimum of 2 years of software engineering experience
- Expertise in multiple programming languages, including Python, JavaScript, and Go
- Deep understanding of cloud technologies, especially AWS and Kubernetes
- Track record of leading high-performing engineering teams
- Strong communication skills and ability to mentor junior developers

**Note:** This position is open to candidates worldwide. Don't miss the chance to join Microsoft Inc. and work on groundbreaking projects!
coreyjonoliver, @rithishsamm, @beaknit, @chidelmun, @deckarts, @jkrage, @Mikhalevich, @bmarika, @omardoma, @Anim-101, @rgrgx, @rohits2290, @sushidub, @msiuts, @jotaoro, @palmerville, @thierrymarianne, @dangerousmanjay, @sysbot, @sbilly

**Comment by nunomazer** [comment]
https://github.com/mazer-dev/pejota
